config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'
  get "/login" => "session#new", as: :login
  post "/login" => "session#create"
  post "/logout" => "session#destroy", as: :logout
  post '/register' => "users#create"
  get '/register' => "users#new", as: :register_page
  get '/setting' => "users#edit", as: :setting
  get '/oauth_callback' => "users#oauth_callback"
  post '/join_group' => 'groups#join'
  post '/leave_group' => 'groups#leave'

  resources :users, only: [:edit, :new, :create]
  resources :groups, except: :index

  
end

app/models/book.rb
class Book < ActiveRecord::Base
  has_many :read_records
end

app/models/book_read.rb
class BookRead < ActiveRecord::Base
end

app/models/douban_auth_info.rb
class DoubanAuthInfo < ActiveRecord::Base
  belongs_to :user
end

app/models/group.rb
class Group < ActiveRecord::Base
  has_and_belongs_to_many :users

  def contain_user user
    users.any? do |user_in_group|
      user_in_group.id == user.id
    end
  end
end

app/models/read_record.rb
class ReadRecord < ActiveRecord::Base
  belongs_to :user
  belongs_to :book
end

app/models/user.rb
# encoding: utf-8
require 'digest'

class User < ActiveRecord::Base
  has_one :douban_auth_info
  has_and_belongs_to_many :groups
  has_many :read_records

  attr_accessor :password

  validates :password, :presence => {:message => "密码不能为空"},
            :confirmation => {:message => "两次输入的密码不一致"},
            :length => { :within => 6..40, too_short: "最少6个字符", too_long: "最多40个字符"}
  validates :email, :presence => {:message => "邮箱不能为空"}
  validates :email, :uniqueness => {:message => "该邮箱已经被占用了"}
  validates_format_of :email,
                      :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i,
                      :message => "邮箱格式不对"

  before_save :encrypt_password

  def has_password?(submitted_password)
    encrypted_password == encrypt(submitted_password)
  end

  def self.authenticate(email, submitted_password)
    user = find_by_email(email)
    return nil if user.nil?
    return user if user.has_password?(submitted_password)
  end

  private
  def encrypt_password
    self.salt = make_salt if new_record?
    self.encrypted_password = encrypt(password) if password
  end

  def encrypt(string)
    secure_hash("#{salt}--#{string}")
  end

  def make_salt
    secure_hash("#{Time.now.utc}--#{password}")
  end

  def secure_hash(string)
    Digest::SHA2.hexdigest(string)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  before_filter :create_user_if_needed

  def current_user
    return @current_user if @current_user
    if session[:current_user].nil?
      return nil
    end
    @current_user = User.find session[:current_user]
  end

  protected
  def create_user_if_needed
    if session[:need_create_new_user]
      redirect_to new_user_path
    end
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy, :join, :leave]

  def show
    @group = Group.includes(:users).find(params[:id])
    @current_user_in_group = @group.users.include? current_user

    if @current_user_in_group
      books = Book.joins(read_records: {user: :groups})
                   .where(groups: {id: @group.id}, read_records:{status: "read"})
                   .distinct

      @book_infos = books.map do |book|
          {
            i_read: book.read_records.map(&:user).include?(current_user),
            book_url: book.url,
            title: book.title,
            read_num: book.read_records.size,
            read_people: book.read_records.map do |read_record|
              {
                  douban_link: "http://book.douban.com/people/#{read_record.user.douban_auth_info.douban_user_id}/",
                  name: read_record.user.douban_auth_info.douban_user_name
              }
            end
        }
      end
      .sort_by{|item| item[:read_num]}
      .reverse
    end
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(group_params)

    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  def join
    @group.users << current_user
    @group.save
    redirect_to root_path
  end

  def leave
    @group.users.delete(current_user.id)
    redirect_to root_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_params
      params[:group].permit(:name, :description)
    end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
	def new
    unless session[:current_user].nil?
      redirect_to root_path
    end
    @user = User.new
	end

	def create
    authenticated_user = User.authenticate(params[:user][:email], params[:user][:password])
    if authenticated_user
      session[:current_user] = authenticated_user.id
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    session[:current_user] = nil
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
require 'douban_client'

class UsersController < ApplicationController

  skip_before_filter :create_user_if_needed, only: [:new, :create]

  def new
    unless session[:need_create_new_user]
      redirect_to root_path
    end
    @user = User.new
  end

  def create
    @user = User.new(params[:user].permit(:email, :password, :password_confirmation))
    if !@user.save
      render :new
      return
    end
    @user.douban_auth_info = DoubanAuthInfo.find (session[:need_create_new_user]["auth_info_id"])
    @user.save

    session[:current_user] = @user.id
    session[:need_create_new_user] = nil

    redirect_to root_path
  end

  def edit
    @user = current_user
  end

  def oauth_callback
    auth_rsp = DoubanClient.token_auth(params[:code])
    if auth_rsp[:status] != 200
      @fails_rsp = auth_rsp
      render "oauth_fail"
      return
    end

    douban_auth_info = DoubanAuthInfo.find_by_douban_user_id(auth_rsp[:auth_info]["douban_user_id"])
    if douban_auth_info.nil?
      douban_auth_info = DoubanAuthInfo.create(auth_rsp[:auth_info])
    end

    if douban_auth_info.user.nil?
      session[:need_create_new_user] = {auth_info_id: douban_auth_info.id}
      redirect_to new_user_path
    else
      session[:current_user] = douban_auth_info.user.id
      redirect_to root_path
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
    if current_user.nil?
      redirect_to login_path
      return
    end

    if current_user.douban_auth_info.nil?
      redirect_to setting_path
      return
    end
    @groups = Group.all
    @joint_groups = @groups.select do |group|
      group.contain_user(current_user)
    end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/users_helper.rb
require "douban_client"

module UsersHelper
  def douban_oauth_url
    DoubanClient.oauth_url
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/groups/_books_info.html.erb
<% book_infos.each do |book_info| %>
	<div>
	<span>
	  <% if book_info[:i_read] %>
		  <%= image_tag("read.jpeg", width: "20px", height: "20px") %>
	  <% end %>
	  <a href="<%= book_info[:book_url] %>" class="book-name"><%= book_info[:title] %></a>
	</span>
	<span>
	  <span>共有<%= book_info[:read_num] %>个人(占团队成员的<%= book_info[:read_num].to_f * 100 / @group.users.size %>
		%)读过本书。</span>

	  	<span class="book-read-users">
		  <span><a class="show-all show_read_users_toggle">点此查看谁读过</a></span>
		  <div class="read_users">
			<ul>
			  <% book_info[:read_people].each do |person| %>
				  <a href="<%= person[:douban_link] %>"><%= person[:name] %></a>
			  <% end %>
			</ul>
		  </div>
		</span>
	</span>
	</div>
<% end %>

app/views/groups/_form.html.erb
<%= form_for(@group) do |f| %>
  <% if @group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
      <% @group.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
	<div class="field">
	  <%= f.label :name, "组名" %><br>
	  <%= f.text_field :name %>
	</div>
	<div class="field">
	  <%= f.label :description, "描述" %><br>
	  <%= f.text_field :description %>
	</div>

	<%= f.submit %>
  </div>
<% end %>

app/views/groups/edit.html.erb
<h1>Editing group</h1>

<%= render 'form' %>

<%= link_to 'Show', @group %> |
<%= link_to 'Back', groups_path %>

app/views/groups/new.html.erb
<h1>New group</h1>

<%= render 'form' %>

<%= link_to 'Back', groups_path %>

app/views/groups/show.html.erb
<p id="notice"><%= notice %></p>


<div class="container">
  <div class="row">
	<div class="group-desc">
	  <span class="field-name">组名：</span>
	  <span class="field-value"><%= @group.name %></span>
	</div>

	<div class="group-desc">
	  <span class="field-name">描述：</span>
	  <span class="field-value"><%= @group.description %></span>
	</div>

	<%= link_to '编辑', edit_group_path(@group), class: "btn btn-primary" %>

	<% if @current_user_in_group %>
		  <span>你已经加入该组，也许你想要</span>
		  <%= form_tag "/leave_group", class: "inline-form" do %>
			  <input name="id" value="<%= @group.id %>" hidden="hidden">
			  <%= submit_tag "退出", class:"btn btn-danger" %>
		  <% end %>
		<div class="line"></div>
		<h2>组员在读的书（总人数<%= @group.users.size %>）</h2>
		<p class="read-prompt">对勾表示你已经读过本书啦：）</p>

		<%= render partial: "books_info", locals: {book_infos: @book_infos.take(3)} %>

		<% if @book_infos.size > 3 %>
			<div><a class="show-all" id="show_more_books_toggle">显示全部</a></div>
			<div id="more_books">
			  <%= render partial: "books_info", locals: {book_infos: @book_infos.drop(3)} %>
			</div>
		<% end %>
	<% else %>
		<%= form_tag "/join_group" do %>
			<input name="id" value="<%= @group.id %>" hidden="hidden">
			<%= submit_tag "加入", class: "btn btn-primary" %>
		<% end %>
	<% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Groupread</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
</head>
<body>

<div class="container">

  <nav class="navbar navbar-default" role="navigation">
	<span class="navbar-brand"><%= link_to "团队阅读", root_path %></span>
	<ul>
	  <span class="right-nav">
	  <% if current_user.nil? %>
		  <span class="navbar-brand"><%= link_to "登录", login_path, class: "btn btn-default navbar-btn fix-logout" %></span>
	  <% else %>

			  <span class="navbar-brand"><%= link_to "我的设置", setting_path %></span>
			  <span class="navbar-brand"><%= form_tag "/logout", class: "inline-form" do %>
				  <%= submit_tag "登出", class: "btn btn-default navbar-btn fix-logout" %>
			  <% end %>
			  </span>

	  <% end %>
		  </span>
	</ul>
  </nav>

  <%= yield %>

</div>

</body>
</html>

app/views/session/new.html.erb
<div class="error-msg"><%= "登录信息有误，请重新输入" if @user.nil? %></div>

<%= form_tag("/login") do %>
	<div class="field">
	  <div><%= label_tag :email, "邮箱"%></div>
	  <%= text_field_tag "user[email]" %>
	</div>
	<div class="field">
	  <div><%= label_tag :password, "密码"%></div>
	  <%= password_field_tag "user[password]" %>
	</div>
	<%= submit_tag "登录", class: "btn btn-primary" %>
	<span>或者</span><a href="<%= douban_oauth_url %>"><%= image_tag "login_with_douban_32.png" %></a>
<% end %>

app/views/users/_info_form.html.erb
<span class="error-msg"><%= @user.errors[:email].first if @user.errors[:email].present? %></span>
<div class="field">
  <div><%= f.label :email, "邮箱:"%><span class="field-notes">（请使用正确的邮箱以便以后可以通过邮箱找回密码）</span></div>
  <%= f.text_field :email %>
</div>

<span class="error-msg"><%= @user.errors[:password].first if @user.errors[:password].present? %></span>
<div class="field">
  <div><%= f.label :password, "密码:"%><span class="field-notes">（6到40位字符）</span></div>
  <%= f.password_field :password %>
</div>

<span class="error-msg"><%= @user.errors[:password_confirmation].first if @user.errors[:password_confirmation].present? %></span>
<div class="field">
  <div><%= f.label :password_confirmation, "再次输入密码:"%></div>
  <%= f.password_field :password_confirmation %>
</div>

app/views/users/edit.html.erb
<% if flash[:authed] %>
	<div>你已经成功的连接到了豆瓣，点击<%= link_to "这里", root_path %>开始使用本站的功能</div>
<% end %>

<%= form_for(@user) do |f|%>
	<div class="field">
	  <%= f.label :email, "邮箱"%>
	  <%= f.text_field :email, disabled: "disable" %>
	</div>
	<% if @user.douban_auth_info.nil? %>
		<div>你还没有绑定豆瓣账号，请先点击右边的图标绑定<a href="<%= douban_oauth_url %>"><%= image_tag "favicon_48x48.png" %></a></div>
	<% else%>
		<div>你已经绑定了豆瓣账号：
		  <%= link_to "#{@user.douban_auth_info.douban_user_name}",
					  "http://book.douban.com/people/#{@user.douban_auth_info.douban_user_id}",
					  class: "douban_person_link"
		  %>
		</div>
		<div>可以点击右边的图标绑定其他的账号<a href="<%= douban_oauth_url %>"><%= image_tag "favicon_48x48.png" %></a></div>
	<% end%>
<% end %>

app/views/users/new.html.erb
<p class="register-info">补全您的信息，这样下次就可以直接通过下面的信息登陆本站了</p>
<%= form_for(@user) do |f|%>
	<%= render partial: "info_form", locals: {f: f} %>
	<%= submit_tag "立即注册", class: "btn btn-primary" %>
<% end %>

app/views/users/oauth_fail.html.erb
<p>似乎和豆瓣连接失败了，错误消息：<%= @auth_rsp[:message] %></p>
<p><%= link_to "点此", root_path %>回到主页</p>

app/views/welcome/index.html.erb
<div class="row">
  <div class="col-xs-6">
	<h4>所有的阅读组</h4>
	<ul class="list-unstyled list">
	  <% @groups.each do |group| %>
		  <li>
			<%= link_to group.name, group_path(group.id) %>
		  </li>
	  <% end %>
	</ul>
	<%= link_to ">创建新的阅读组", new_group_path %>
  </div>

  <div class="col-xs-6 list">
	<h4>你已经加入的阅读组</h4>
	<ul class="list-unstyled">
	  <% @joint_groups.each do |group| %>
		  <li>
			<%= link_to group.name, group_path(group.id) %>
		  </li>
	  <% end %>
	</ul>
  </div>
  <div class="col-xs-2"></div>
</div>